<?php

namespace Container6M3ZgA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WLq0UXGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WLq0UXG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WLq0UXG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blogRepository' => ['privates', 'App\\Repository\\BlogRepository', 'getBlogRepositoryService', true],
        ], [
            'blogRepository' => 'App\\Repository\\BlogRepository',
        ]);
    }
}
