<?php

namespace ContainerQWph8ej;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__OjQiauService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..OjQiau' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..OjQiau'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::addBlog' => ['privates', '.service_locator.HTuVFuA', 'get_ServiceLocator_HTuVFuAService', true],
            'App\\Controller\\BlogController::article' => ['privates', '.service_locator.ufVACkK', 'get_ServiceLocator_UfVACkKService', true],
            'App\\Controller\\BlogController::editBlog' => ['privates', '.service_locator.IOHM_EU', 'get_ServiceLocator_IOHMEUService', true],
            'App\\Controller\\BlogController::removeBlog' => ['privates', '.service_locator.A_TABBl', 'get_ServiceLocator_ATABBlService', true],
            'App\\Controller\\CommentController::removeComment' => ['privates', '.service_locator..VsxQ12', 'get_ServiceLocator__VsxQ12Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.WLq0UXG', 'get_ServiceLocator_WLq0UXGService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BlogController:addBlog' => ['privates', '.service_locator.HTuVFuA', 'get_ServiceLocator_HTuVFuAService', true],
            'App\\Controller\\BlogController:article' => ['privates', '.service_locator.ufVACkK', 'get_ServiceLocator_UfVACkKService', true],
            'App\\Controller\\BlogController:editBlog' => ['privates', '.service_locator.IOHM_EU', 'get_ServiceLocator_IOHMEUService', true],
            'App\\Controller\\BlogController:removeBlog' => ['privates', '.service_locator.A_TABBl', 'get_ServiceLocator_ATABBlService', true],
            'App\\Controller\\CommentController:removeComment' => ['privates', '.service_locator..VsxQ12', 'get_ServiceLocator__VsxQ12Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.WLq0UXG', 'get_ServiceLocator_WLq0UXGService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BlogController::addBlog' => '?',
            'App\\Controller\\BlogController::article' => '?',
            'App\\Controller\\BlogController::editBlog' => '?',
            'App\\Controller\\BlogController::removeBlog' => '?',
            'App\\Controller\\CommentController::removeComment' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BlogController:addBlog' => '?',
            'App\\Controller\\BlogController:article' => '?',
            'App\\Controller\\BlogController:editBlog' => '?',
            'App\\Controller\\BlogController:removeBlog' => '?',
            'App\\Controller\\CommentController:removeComment' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
