<?php

namespace ContainerQWph8ej;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IOHMEUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IOHM_EU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IOHM_EU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blogType' => ['privates', 'App\\Form\\EditBlogType', 'getEditBlogTypeService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'blogType' => 'App\\Form\\EditBlogType',
            'entityManager' => '?',
            'slugger' => '?',
        ]);
    }
}
