<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQWph8ej\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQWph8ej/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQWph8ej.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQWph8ej\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQWph8ej\App_KernelDevDebugContainer([
    'container.build_hash' => 'QWph8ej',
    'container.build_id' => '1cf0cf22',
    'container.build_time' => 1638952394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQWph8ej');
